name: Emulator Runner

on:
  workflow_dispatch:


jobs:
  instrumentation-tests:
    name: Instrumentation tests
    runs-on: self-hosted
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        api-level: [ 31 ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: arm64-v8a
          script: ./gradlew connectedDebugAndroidTest
